name: Scrape NAFDAC Alerts

on:
  schedule:
    # Run every 6 minutes: https://crontab.guru/#*/6_*_*_*_*
    - cron: '*/6 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run NAFDAC Alert Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          EXTERNAL_SCRAPER_TOKEN: ${{ secrets.EXTERNAL_SCRAPER_TOKEN }}
          AD_EMAIL: ${{ secrets.AD_EMAIL }}
        run: |
          # Start the development server in background
          npm run dev &
          SERVER_PID=$!

          # Wait for server to be ready (simple wait - adjust as needed)
          sleep 10

          # Run the scraper (local mode = 2 alerts max, skips duplicates)
          npm run scrape:local

          # Kill background server
          kill $SERVER_PID 2>/dev/null || true
